item {
  id: 1
  name: 'blazer'
}

item {
  id: 2
  name: 'borka'
}

item {
  id: 3
  name: 'dhuti'
}

item {
  id: 4
  name: 'fotua'
}

item {
  id: 5
  name: 'hijab'
}

item {
  id: 6
  name: 'jacket'
}

item {
  id: 7
  name: 'kamiz'
}

item {
  id: 8
  name: 'lungi'
}

item {
  id: 9
  name: 'panjabi'
}

item {
  id: 10
  name: 'pant'
}

item {
  id: 11
  name: 'shari'
}

item {
  id: 12
  name: 'shirt'
}

item {
  id: 13
  name: 'sweater'
}

item {
  id: 14
  name: 't-shirt'
}
